name: Release

on:
  workflow_dispatch:
  push:
    branches:
     - main
  
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: papeloto/action-zip@v1
        with:
          files: UnityRSocket/Assets/Viglucci
          dest: out/UnityRSocket-${{ steps.semantic-release.outputs.new_release_version}}.zip

      - name: Attach Artifacts
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/UnityRSocket-${{ steps.semantic-release.outputs.new_release_version}}.zip
          file_glob: true
          overwrite: true
          body: ${{ steps.semantic-release.outputs.new_release_notes}}
          tag: v${{ steps.semantic-release.outputs.new_release_version}}