namespace Viglucci.UnityRSocket.Metadata
{
    public enum WellKnownMimeType
    {
        UNPARSEABLE_MIME_TYPE = -2,
        UNKNOWN_RESERVED_MIME_TYPE = -1,
        APPLICATION_AVRO = 0x00,
        APPLICATION_CBOR = 0x01,
        APPLICATION_GRAPHQL = 0x02,
        APPLICATION_GZIP = 0x03,
        APPLICATION_JAVASCRIPT = 0x04,
        APPLICATION_JSON = 0x05,
        APPLICATION_OCTET_STREAM = 0x07,
        APPLICATION_THRIFT = 0x08,
        APPLICATION_PROTOBUF = 0x09,
        APPLICATION_XML = 0x0a,
        APPLICATION_ZIP = 0x0b,
        AUDIO_AAC = 0x0c,
        AUDIO_MP3 = 0x0d,
        AUDIO_MP4 = 0x0e,
        AUDIO_MPEG3 = 0x0f,
        AUDIO_MPEG = 0x10,
        AUDIO_OGG = 0x11,
        AUDIO_OPUS = 0x12,
        AUDIO_VORBIS = 0x13,
        IMAGE_BMP = 0x14,
        IMAGE_GIG = 0x15,
        IMAGE_HEIC_SEQUENCE = 0x16,
        IMAGE_HEIC = 0x17,
        IMAGE_HEIF_SEQUENCE = 0x18,
        IMAGE_HEIF = 0x19,
        IMAGE_JPEG = 0x1a,
        IMAGE_PNG = 0x1b,
        IMAGE_TIFF = 0x1c,
        MULTIPART_MIXED = 0x1d,
        TEXT_CSS = 0x1e,
        TEXT_CSV = 0x1f,
        TEXT_HTML = 0x20,
        TEXT_PLAIN = 0x21,
        TEXT_XML = 0x22,
        VIDEO_H264 = 0x23,
        VIDEO_H265 = 0x24,
        VIDEO_VP8 = 0x25,
        APPLICATION_HESSIAN = 0x26,
        APPLICATION_JAVA_OBJECT = 0x27,
        APPLICATION_CLOUDEVENTS_JSON = 0x28,
        MESSAGE_RSOCKET_MIMETYPE = 0x7a,
        MESSAGE_RSOCKET_ACCEPT_MIMETYPES = 0x7b,
        MESSAGE_RSOCKET_AUTHENTICATION = 0x7c,
        MESSAGE_RSOCKET_TRACING_ZIPKIN = 0x7d,
        MESSAGE_RSOCKET_ROUTING = 0x7e,
        MESSAGE_RSOCKET_COMPOSITE_METADATA = 0x7f,
    }
}